import { ImageAnalysisResult, SunoPrompt } from '../types';

export const generateMarkdown = (
  analysisResult: ImageAnalysisResult,
  sunoPrompt: SunoPrompt
): string => {
  return `# 🎨 Visual Inspiration to Music - 창작 결과물

## 📸 이미지 분석 결과

### 내용 설명
${analysisResult.description}

### 분위기 & 감정
${analysisResult.mood.map(m => `- ${m}`).join('\n')}

### 전체 분위기
${analysisResult.atmosphere}

### 색상 팔레트
${analysisResult.colorPalette.map(c => `- ${c}`).join('\n')}

### 추천 장르
${analysisResult.suggestedGenre.map(g => `- ${g}`).join('\n')}

### 주제 & 테마
${analysisResult.themes.map(t => `- ${t}`).join('\n')}

---

## 🎵 Suno AI 음악 프롬프트

### Song Title
**${sunoPrompt.songTitle}**

### Lyric Concept
${sunoPrompt.lyricConcept}

### Music Style & Genre
${sunoPrompt.musicStyle}

### Mood & Tempo
${sunoPrompt.moodAndTempo}

${sunoPrompt.specialInstructions ? `### Special Instructions\n${sunoPrompt.specialInstructions}\n` : ''}

---

## 📝 Complete Suno Prompt

\`\`\`
${sunoPrompt.fullPrompt}
\`\`\`

---

*Generated by Visual Inspiration to Music Creator*
*Powered by Claude AI*
`;
};

export const downloadMarkdown = (
  analysisResult: ImageAnalysisResult,
  sunoPrompt: SunoPrompt,
  filename: string = 'music-creation-note.md'
): void => {
  const markdown = generateMarkdown(analysisResult, sunoPrompt);
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const copyToClipboard = async (text: string): Promise<void> => {
  try {
    await navigator.clipboard.writeText(text);
  } catch (error) {
    console.error('Failed to copy to clipboard:', error);
    throw new Error('클립보드 복사에 실패했습니다.');
  }
};
